apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: opendidac
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: "eval-dev"
  POSTGRES_PASSWORD: "eval-dev"
  POSTGRES_DB: "eval-dev"
