apiVersion: v1
kind: Secret
metadata:
  name: opendidac-app-secret
  namespace: opendidac
  labels:
    app: opendidac-web
type: Opaque
stringData:
  DATABASE_URL: "postgresql://eval-dev:eval-dev@postgres:5432/eval-dev"
  NEXTAUTH_URL: "http://opendidac.local"
  NEXTAUTH_SECRET: "5msBu1RJUMMuHnDaMnbkYI3XiyUXFSPB"
  NEXTAUTH_KEYCLOAK_CLIENT_ID: "opendidac-web"
  NEXTAUTH_KEYCLOAK_CLIENT_SECRET: "5msBu1RJUMMuHnDaMnbkYI3XiyUXFSPB"
  NEXTAUTH_KEYCLOAK_ISSUER_BASE_URL: "http://keycloak.opendidac.svc:8080/realms/opendidac"
  NEXTAUTH_KEYCLOAK_INTERNAL_BASE_URL: "http://keycloak:8080/realms/opendidac"
