apiVersion: v1
kind: Service
metadata:
  name: opendidac-web
  namespace: opendidac
  labels:
    app: opendidac-web
spec:
  type: LoadBalancer
  selector:
    app: opendidac-web
  ports:
    - name: http
      port: 80
      targetPort: 3000
